version: "2"
services:
    db:
        image:   mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: on-failure
        ports:
                 - "3303:3306"
        volumes:
                 - ./db:/var/lib/mysql
        environment:
                 MYSQL_ROOT_PASSWORD: fobloi56
                 MYSQL_DATABASE: mysqldb
                 MYSQL_USER: tnt
                 MYSQL_PASSWORD: tnt
    backend:
        image:   tigrondev/tp-sm1-web-djangoapp
        restart:  on-failure
        ports:
                  - "1488:1488"
        depends_on:
                  - db
        volumes:
                  - ./tp-sm1-web-djangoapp/django-app:/srv/backend_server
    frontend:
        image:   tigrondev/tp-sm1-web-frontserv
        ports:
                 - "8080:80"
        depends_on:
                 - backend
